---
- name: Create nextcloud directory
  file:
    path: /srv/nextcloud
    state: directory
    mode: '0750'
    recurse: yes

- name: Create conf directory
  copy:
    src: conf
    dest: /srv/nextcloud/

- name: Create docker-compose file
  template:
    src: docker-compose.yml
    dest: /srv/nextcloud/docker-compose.yml
